### ISSUE TITLE
Pin 35 on ice40up5k SG48 cannot be assigned as clock input

### ISSUE THREAD

**Issue by zeusima** [cliffordwolf/icestorm#142]
top.v:

```
module top(input clk, output clkin, clkout, lock);
	SB_PLL40_CORE #(
		.FEEDBACK_PATH("SIMPLE"),
		.PLLOUT_SELECT("GENCLK"),
		.DIVR(4'b0000),
		.DIVF(7'b1000010),
		.DIVQ(3'b101),
		.FILTER_RANGE(3'b001)
	) uut (
		.LOCK(lock),
		.RESETB(1'b1),
		.BYPASS(1'b0),
		.REFERENCECLK(clk),
		.PLLOUTCORE(clkout)
	);
	assign clkin = clk;
endmodule
```

pcf file:

```
set_io clk 35
set_io clkin 12
set_io clkout 21
set_io lock 13
```

When I run this through the icestorm tools and run pnr I get the following printed:

fatal error: failed to place: placed 0 PLLs of 1 / 1

Pins other than pin 35 can be assigned to the signal "clk" (I tried a few of the other clock buffer pins). This is a problem for the ice40up5k breakout as pin 35 is the pin which the xtal oscillator is connected to.

Let me know if I'm doing something incorrectly or if this is a valid issue.

**Comment by daveshah1** [comment]
Two problems:
 - As pin 35 is a dedicated PLL input, the _CORE PLL primitive variants cannot be used. Instead one of the _PAD variants, and the PACKAGEPIN input instead of REFERENCECLK input must be used.
 - If you also need the input clock, you must use SB_PLL40_2_PAD variant to pass through the input clock too.

**Comment by zeusima** [comment]
Thanks very much Dave, I made the necessary modifications and the design now works as expected.
